# https://docs.travis-ci.com/user/languages/php/
language: php
sudo: required
dist: trusty
group: edge
php:
  - '7.1'
  - '7.2'

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

install:
  - composer install
  - composer dump-autoload

after_success:
    - bash <(curl -s https://codecov.io/bash)
